# Generated by Django 4.1.5 on 2023-01-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('junior', 'Начинающий'), ('middle', 'Продолжающий'), ('pro', 'Продвинутый')], max_length=15)),
                ('course', models.ManyToManyField(to='main_page.course')),
            ],
        ),
    ]
