# Generated by Django 4.1.5 on 2023-01-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_courselevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_name',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
